### ISSUE TITLE
ValueError: You shouldn't create CalibrationPoint objects yourself

### ISSUE THREAD

**Issue by chiara-gambi** [yh-luo/psychopy_tobii_infant#18]
Many thanks for sharing this project. I have been using your tobii-infant-controller in an experiment, programmed in Psychopy3 and interfacing via iohub to a tobii X2-60 (running on Windows 7).

I get the following error message occasionally (copying the entire Psychopy console output for context):

> Welcome to PsychoPy3!
> v2021.1.2
> 12.8191     WARNING     Couldn't connect to psychopy.org
> Check internet settings (and proxy setting in PsychoPy Preferences.
> 28.6397     INFO     Loaded monitor calibration from ['2022_01_24 11:57']
> Generating PsychoPy script...
> 
> Running: C:\Users\Eyetracker2\Documents\StructureEyes\StructureEyes_final\Task\_pred_struct_final_lastrun.py 
> 34.6018     INFO     Loaded monitor calibration from ['2022_01_24 11:57']
> pygame 1.9.6
> Hello from the pygame community. https://www.pygame.org/contribute.html
> 29.0727     WARNING     t of last frame was 20.48ms (=1/48)
> 47.1880     WARNING     Monitor specification not found. Creating a temporary one...
> pressed e at 0.1514297748599347 ms
> 1070.5146     WARNING     Monitor specification not found. Creating a temporary one...
> 2122.6566     WARNING     Monitor specification not found. Creating a temporary one...
> ioHub Server Process Completed With Code:  0
> Traceback (most recent call last):
>   File "C:\Users\Eyetracker2\Documents\StructureEyes\StructureEyes_final\Task\_pred_struct_final_lastrun.py", line 2326, in <module>
>     controller.run_calibration(CALIPOINTS, decision_key='a')
>   File "C:\Users\Eyetracker2\Documents\StructureEyes\StructureEyes_final\Task\psychopy_tobii_infant\__init__.py", line 718, in run_calibration
>     self.calibration_result = self.calibration.compute_and_apply()
>   File "C:\Program Files\PsychoPy3\lib\site-packages\tobiiresearch\implementation\ScreenBasedCalibration.py", line 270, in compute_and_apply
>     calibration_points.append(CalibrationPoint(position, tuple(calibration_samples)))
>   File "C:\Program Files\PsychoPy3\lib\site-packages\tobiiresearch\implementation\ScreenBasedCalibration.py", line 87, in __init__
>     "You shouldn't create CalibrationPoint objects yourself.")
> ValueError: You shouldn't create CalibrationPoint objects yourself.
> Error in atexit._run_exitfuncs:
> Traceback (most recent call last):
>   File "C:\Users\Eyetracker2\Documents\StructureEyes\StructureEyes_final\Task\psychopy_tobii_infant\__init__.py", line 629, in close
>     "Data file is not found. Use start_recording() to record and "
> RuntimeWarning: Data file is not found. Use start_recording() to record and save the data.
> Experiment ended.

I have been in touch with Tobii support and also posted on the Psychpy Ddiscourse forum, but no luck. I am puzzled because the issue does not happen deterministically. Tobii support think the problem is not hardware-related. Attaching the psychopy program file. Thanks. 

[structure_pred_for_github.zip](https://github.com/yh-luo/psychopy_tobii_infant/files/9549257/structure_pred_for_github.zip)

**Comment by yh-luo** [comment]
Hmm, the error message showed that `tobii-research` complained the instantiation of `CalibrationPoint`, which is how `psychopy_tobii_infant` utilizes for calibration. I don't remember encountering this problem before. It could result from the changes of newer version of `tobii-search`.

Could you provide the versions of PsychoPy, `tobii-research` and Python? Thanks!

**Comment by chiara-gambi** [comment]
Hi thanks for getting back so quickly,

Psychopy version 2021.2.1.0, tobii-research version 1.7.3. Apologies I
don't have access to the computer right now to check the Python version,
but it was installed together with Psychopy, so it would be whatever comes
with that release of Psychopy I think?

Chiara

**Comment by yh-luo** [comment]
Hello @chiara-gambi
Sorry for the late reply, I got caught up by work lately.
I've looked into the attached Python file and had a feeling that the problem results from bad calibration results?
Does the problem happen when the participant look away during data collection for the calibration points?

Since the package was developed with `tobii-research` 1.7.0, I'm afraid that it might not work well with newer versions of `tobii-research`.
